QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH += \
    src \
    src/qt \
    src/ui \
    src/libhv \
    src/libhv/base \
    src/libhv/cpputil

SOURCES += \
    main.cpp \
    mainwindow.cpp \
    src/libhv/base/hbase.c \
    src/libhv/base/herr.c \
    src/libhv/base/hlog.c \
    src/libhv/base/hmain.c \
    src/libhv/base/hsocket.c \
    src/libhv/base/htime.c \
    src/libhv/base/hversion.c \
    src/libhv/base/rbtree.c \
    src/libhv/cpputil/RAII.cpp \
    src/libhv/cpputil/ThreadLocalStorage.cpp \
    src/libhv/cpputil/hasync.cpp \
    src/libhv/cpputil/hdir.cpp \
    src/libhv/cpputil/hpath.cpp \
    src/libhv/cpputil/hstring.cpp \
    src/libhv/cpputil/hurl.cpp \
    src/libhv/cpputil/ifconfig.cpp \
    src/libhv/cpputil/iniparser.cpp \
    src/libhv/echo-servers/asio_echo.cpp \
    src/libhv/echo-servers/libev_echo.c \
    src/libhv/echo-servers/libevent_echo.c \
    src/libhv/echo-servers/libhv_echo.c \
    src/libhv/echo-servers/libuv_echo.c \
    src/libhv/echo-servers/muduo_echo.cpp \
    src/libhv/echo-servers/pingpong_client.cpp \
    src/libhv/echo-servers/poco_echo.cpp \
    src/libhv/event/epoll.c \
    src/libhv/event/evport.c \
    src/libhv/event/hevent.c \
    src/libhv/event/hloop.c \
    src/libhv/event/iocp.c \
    src/libhv/event/kcp/hkcp.c \
    src/libhv/event/kcp/ikcp.c \
    src/libhv/event/kqueue.c \
    src/libhv/event/nio.c \
    src/libhv/event/nlog.c \
    src/libhv/event/noevent.c \
    src/libhv/event/overlapio.c \
    src/libhv/event/poll.c \
    src/libhv/event/rudp.c \
    src/libhv/event/select.c \
    src/libhv/event/unpack.c \
    src/libhv/evpp/EventLoopThreadPool_test.cpp \
    src/libhv/evpp/EventLoopThread_test.cpp \
    src/libhv/evpp/EventLoop_test.cpp \
    src/libhv/evpp/TcpClientEventLoop_test.cpp \
    src/libhv/evpp/TcpClient_test.cpp \
    src/libhv/evpp/TcpServer_test.cpp \
    src/libhv/evpp/TimerThread_test.cpp \
    src/libhv/evpp/UdpClient_test.cpp \
    src/libhv/evpp/UdpServer_test.cpp \
    src/libhv/examples/consul/consul.cpp \
    src/libhv/examples/consul/main.cpp \
    src/libhv/examples/curl.cpp \
    src/libhv/examples/hloop_test.c \
    src/libhv/examples/hmain_test.cpp \
    src/libhv/examples/htimer_test.c \
    src/libhv/examples/http_client_test.cpp \
    src/libhv/examples/http_server_test.cpp \
    src/libhv/examples/httpd/handler.cpp \
    src/libhv/examples/httpd/httpd.cpp \
    src/libhv/examples/httpd/router.cpp \
    src/libhv/examples/jsonrpc/cJSON.c \
    src/libhv/examples/jsonrpc/jsonrpc_client.c \
    src/libhv/examples/jsonrpc/jsonrpc_server.c \
    src/libhv/examples/mqtt/mqtt_client_test.cpp \
    src/libhv/examples/mqtt/mqtt_pub.c \
    src/libhv/examples/mqtt/mqtt_sub.c \
    src/libhv/examples/multi-thread/multi-acceptor-processes.c \
    src/libhv/examples/multi-thread/multi-acceptor-threads.c \
    src/libhv/examples/multi-thread/one-acceptor-multi-workers.c \
    src/libhv/examples/nc.c \
    src/libhv/examples/nmap/main.cpp \
    src/libhv/examples/nmap/nmap.cpp \
    src/libhv/examples/protorpc/protorpc.c \
    src/libhv/examples/protorpc/protorpc_client.cpp \
    src/libhv/examples/protorpc/protorpc_server.cpp \
    src/libhv/examples/qt/client/HttpClientPage.cpp \
    src/libhv/examples/qt/client/TcpClientPage.cpp \
    src/libhv/examples/qt/client/UdpClientPage.cpp \
    src/libhv/examples/qt/client/WebSocketClientPage.cpp \
    src/libhv/examples/qt/client/main.cpp \
    src/libhv/examples/qt/client/mainwindow.cpp \
    src/libhv/examples/qt/server/HttpServerPage.cpp \
    src/libhv/examples/qt/server/TcpServerPage.cpp \
    src/libhv/examples/qt/server/UdpServerPage.cpp \
    src/libhv/examples/qt/server/main.cpp \
    src/libhv/examples/qt/server/mainwindow.cpp \
    src/libhv/examples/socks5_proxy_server.c \
    src/libhv/examples/tcp_chat_server.c \
    src/libhv/examples/tcp_client_test.c \
    src/libhv/examples/tcp_echo_server.c \
    src/libhv/examples/tcp_proxy_server.c \
    src/libhv/examples/tinyhttpd.c \
    src/libhv/examples/tinyproxyd.c \
    src/libhv/examples/udp_echo_server.c \
    src/libhv/examples/udp_proxy_server.c \
    src/libhv/examples/websocket_client_test.cpp \
    src/libhv/examples/websocket_server_test.cpp \
    src/libhv/examples/wget.cpp \
    src/libhv/examples/wrk.cpp \
    src/libhv/http/Http1Parser.cpp \
    src/libhv/http/Http2Parser.cpp \
    src/libhv/http/HttpMessage.cpp \
    src/libhv/http/HttpParser.cpp \
    src/libhv/http/WebSocketParser.cpp \
    src/libhv/http/client/AsyncHttpClient.cpp \
    src/libhv/http/client/WebSocketClient.cpp \
    src/libhv/http/client/http_client.cpp \
    src/libhv/http/http_content.cpp \
    src/libhv/http/http_parser.c \
    src/libhv/http/httpdef.c \
    src/libhv/http/multipart_parser.c \
    src/libhv/http/server/FileCache.cpp \
    src/libhv/http/server/HttpHandler.cpp \
    src/libhv/http/server/HttpServer.cpp \
    src/libhv/http/server/HttpService.cpp \
    src/libhv/http/server/http_page.cpp \
    src/libhv/http/websocket_parser.c \
    src/libhv/http/wsdef.c \
    src/libhv/mqtt/mqtt_client.c \
    src/libhv/mqtt/mqtt_protocol.c \
    src/libhv/protocol/dns.c \
    src/libhv/protocol/ftp.c \
    src/libhv/protocol/icmp.c \
    src/libhv/protocol/smtp.c \
    src/libhv/ssl/appletls.c \
    src/libhv/ssl/gnutls.c \
    src/libhv/ssl/hssl.c \
    src/libhv/ssl/mbedtls.c \
    src/libhv/ssl/nossl.c \
    src/libhv/ssl/openssl.c \
    src/libhv/ssl/wintls.c \
    src/libhv/unittest/base64_test.c \
    src/libhv/unittest/connect_test.c \
    src/libhv/unittest/date_test.c \
    src/libhv/unittest/defer_test.cpp \
    src/libhv/unittest/ftp_test.c \
    src/libhv/unittest/hatomic_test.c \
    src/libhv/unittest/hatomic_test.cpp \
    src/libhv/unittest/hbase_test.c \
    src/libhv/unittest/hmutex_test.c \
    src/libhv/unittest/hpath_test.cpp \
    src/libhv/unittest/hstring_test.cpp \
    src/libhv/unittest/hthread_test.cpp \
    src/libhv/unittest/hurl_test.cpp \
    src/libhv/unittest/ifconfig_test.cpp \
    src/libhv/unittest/listdir_test.cpp \
    src/libhv/unittest/md5_test.c \
    src/libhv/unittest/mkdir_test.c \
    src/libhv/unittest/nslookup_test.c \
    src/libhv/unittest/objectpool_test.cpp \
    src/libhv/unittest/ping_test.c \
    src/libhv/unittest/rbtree_test.c \
    src/libhv/unittest/rmdir_test.c \
    src/libhv/unittest/sendmail_test.c \
    src/libhv/unittest/sha1_test.c \
    src/libhv/unittest/sizeof_test.cpp \
    src/libhv/unittest/socketpair_test.c \
    src/libhv/unittest/synchronized_test.cpp \
    src/libhv/unittest/threadpool_test.cpp \
    src/libhv/unittest/webbench.c \
    src/libhv/util/base64.c \
    src/libhv/util/md5.c \
    src/libhv/util/sha1.c \
    src/main.cpp \
    src/mainwindow.cpp \
    src/ui/mainwindow.cpp

HEADERS += \
    appdef.h \
    confile.h \
    mainwindow.h \
    src/appdef.h \
    src/confile.h \
    src/libhv/base/array.h \
    src/libhv/base/hatomic.h \
    src/libhv/base/hbase.h \
    src/libhv/base/hbuf.h \
    src/libhv/base/hdef.h \
    src/libhv/base/heap.h \
    src/libhv/base/hendian.h \
    src/libhv/base/herr.h \
    src/libhv/base/hlog.h \
    src/libhv/base/hmain.h \
    src/libhv/base/hmath.h \
    src/libhv/base/hmutex.h \
    src/libhv/base/hplatform.h \
    src/libhv/base/hproc.h \
    src/libhv/base/hsocket.h \
    src/libhv/base/hsysinfo.h \
    src/libhv/base/hthread.h \
    src/libhv/base/htime.h \
    src/libhv/base/hversion.h \
    src/libhv/base/list.h \
    src/libhv/base/netinet.h \
    src/libhv/base/queue.h \
    src/libhv/base/rbtree.h \
    src/libhv/cpputil/ThreadLocalStorage.h \
    src/libhv/cpputil/hasync.h \
    src/libhv/cpputil/hdir.h \
    src/libhv/cpputil/hfile.h \
    src/libhv/cpputil/hmap.h \
    src/libhv/cpputil/hobjectpool.h \
    src/libhv/cpputil/hpath.h \
    src/libhv/cpputil/hscope.h \
    src/libhv/cpputil/hstring.h \
    src/libhv/cpputil/hthreadpool.h \
    src/libhv/cpputil/hurl.h \
    src/libhv/cpputil/ifconfig.h \
    src/libhv/cpputil/iniparser.h \
    src/libhv/cpputil/json.hpp \
    src/libhv/cpputil/singleton.h \
    src/libhv/event/hevent.h \
    src/libhv/event/hloop.h \
    src/libhv/event/iowatcher.h \
    src/libhv/event/kcp/hkcp.h \
    src/libhv/event/kcp/ikcp.h \
    src/libhv/event/nlog.h \
    src/libhv/event/overlapio.h \
    src/libhv/event/rudp.h \
    src/libhv/event/unpack.h \
    src/libhv/evpp/Buffer.h \
    src/libhv/evpp/Channel.h \
    src/libhv/evpp/Event.h \
    src/libhv/evpp/EventLoop.h \
    src/libhv/evpp/EventLoopThread.h \
    src/libhv/evpp/EventLoopThreadPool.h \
    src/libhv/evpp/Status.h \
    src/libhv/evpp/TcpClient.h \
    src/libhv/evpp/TcpServer.h \
    src/libhv/evpp/TimerThread.h \
    src/libhv/evpp/UdpClient.h \
    src/libhv/evpp/UdpServer.h \
    src/libhv/examples/consul/consul.h \
    src/libhv/examples/httpd/handler.h \
    src/libhv/examples/httpd/router.h \
    src/libhv/examples/jsonrpc/cJSON.h \
    src/libhv/examples/jsonrpc/handler.h \
    src/libhv/examples/jsonrpc/router.h \
    src/libhv/examples/nmap/nmap.h \
    src/libhv/examples/protorpc/handler/calc.h \
    src/libhv/examples/protorpc/handler/handler.h \
    src/libhv/examples/protorpc/handler/login.h \
    src/libhv/examples/protorpc/protorpc.h \
    src/libhv/examples/protorpc/router.h \
    src/libhv/examples/qt/client/HttpClientPage.h \
    src/libhv/examples/qt/client/TcpClientPage.h \
    src/libhv/examples/qt/client/UdpClientPage.h \
    src/libhv/examples/qt/client/WebSocketClientPage.h \
    src/libhv/examples/qt/client/customevent.h \
    src/libhv/examples/qt/client/mainwindow.h \
    src/libhv/examples/qt/server/HttpServerPage.h \
    src/libhv/examples/qt/server/TcpServerPage.h \
    src/libhv/examples/qt/server/UdpServerPage.h \
    src/libhv/examples/qt/server/customevent.h \
    src/libhv/examples/qt/server/mainwindow.h \
    src/libhv/hconfig.h \
    src/libhv/hconfig.h.in \
    src/libhv/hexport.h \
    src/libhv/http/Http1Parser.h \
    src/libhv/http/Http2Parser.h \
    src/libhv/http/HttpMessage.h \
    src/libhv/http/HttpParser.h \
    src/libhv/http/WebSocketChannel.h \
    src/libhv/http/WebSocketParser.h \
    src/libhv/http/client/AsyncHttpClient.h \
    src/libhv/http/client/WebSocketClient.h \
    src/libhv/http/client/axios.h \
    src/libhv/http/client/http_client.h \
    src/libhv/http/client/requests.h \
    src/libhv/http/grpcdef.h \
    src/libhv/http/http2def.h \
    src/libhv/http/http_content.h \
    src/libhv/http/http_parser.h \
    src/libhv/http/httpdef.h \
    src/libhv/http/multipart_parser.h \
    src/libhv/http/server/FileCache.h \
    src/libhv/http/server/HttpContext.h \
    src/libhv/http/server/HttpHandler.h \
    src/libhv/http/server/HttpResponseWriter.h \
    src/libhv/http/server/HttpServer.h \
    src/libhv/http/server/HttpService.h \
    src/libhv/http/server/WebSocketServer.h \
    src/libhv/http/server/http_page.h \
    src/libhv/http/websocket_parser.h \
    src/libhv/http/wsdef.h \
    src/libhv/hv.h \
    src/libhv/misc/grpc_server.h \
    src/libhv/misc/win32_getopt.h \
    src/libhv/mqtt/mqtt_client.h \
    src/libhv/mqtt/mqtt_protocol.h \
    src/libhv/protocol/dns.h \
    src/libhv/protocol/ftp.h \
    src/libhv/protocol/icmp.h \
    src/libhv/protocol/smtp.h \
    src/libhv/ssl/hssl.h \
    src/libhv/util/base64.h \
    src/libhv/util/md5.h \
    src/libhv/util/sha1.h \
    src/mainwindow.h \
    src/qt/qtfunctions.h \
    src/qt/qtheaders.h \
    src/ui/mainwindow.h \
    src/ui/qtstyles.h

FORMS += \
    mainwindow.ui \
    src/mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

SUBDIRS += \
    src/libhv/examples/qt/client/client.pro \
    src/libhv/examples/qt/server/server.pro

DISTFILES += \
    src/libhv/.clang-format \
    src/libhv/.gitattributes \
    src/libhv/.gitignore \
    src/libhv/.travis.yml \
    src/libhv/BUILD.md \
    src/libhv/CMakeLists.txt \
    src/libhv/LICENSE \
    src/libhv/README-CN.md \
    src/libhv/README.md \
    src/libhv/TREE.md \
    src/libhv/base/README.md \
    src/libhv/cert/cacert.pem \
    src/libhv/cert/gen.sh \
    src/libhv/cert/server.crt \
    src/libhv/cert/server.key \
    src/libhv/cmake/ios.toolchain.cmake \
    src/libhv/cmake/libhvConfig.cmake \
    src/libhv/cmake/utils.cmake \
    src/libhv/cmake/vars.cmake \
    src/libhv/config.ini \
    src/libhv/config.mk \
    src/libhv/configure \
    src/libhv/cpputil/README.md \
    src/libhv/docs/API.md \
    src/libhv/docs/PLAN.md \
    src/libhv/echo-servers/benchmark.sh \
    src/libhv/echo-servers/build.sh \
    src/libhv/etc/hmain_test.conf \
    src/libhv/etc/httpd.conf \
    src/libhv/etc/nginx.conf \
    src/libhv/event/README.md \
    src/libhv/evpp/README.md \
    src/libhv/evpp/build_test.sh \
    src/libhv/examples/CMakeLists.txt \
    src/libhv/examples/README.md \
    src/libhv/examples/protorpc/proto/base.proto \
    src/libhv/examples/protorpc/proto/calc.proto \
    src/libhv/examples/protorpc/proto/login.proto \
    src/libhv/examples/protorpc/proto/protoc.sh \
    src/libhv/examples/qt/README.md \
    src/libhv/getting_started.sh \
    src/libhv/html/EventSource.html \
    src/libhv/html/WebSocket.html \
    src/libhv/html/downloads/libhv-vs-nginx.png \
    src/libhv/html/downloads/中文.html \
    src/libhv/html/error.html \
    src/libhv/html/index.html \
    src/libhv/html/uploads/upload.sh \
    src/libhv/http/README.md \
    src/libhv/protocol/README.md \
    src/libhv/scripts/check.sh \
    src/libhv/scripts/cmake_cross_compile.sh \
    src/libhv/scripts/consul.py \
    src/libhv/scripts/consul_agent.sh \
    src/libhv/scripts/coredump.sh \
    src/libhv/scripts/create_repo.sh \
    src/libhv/scripts/libhv.cmake \
    src/libhv/scripts/shini.sh \
    src/libhv/scripts/test-coverage.sh \
    src/libhv/scripts/toolchain.sh \
    src/libhv/scripts/unittest.sh \
    src/libhv/unittest/CMakeLists.txt \
    src/libhv/util/README.md
